#Le.Zhang@TECH.BSP.Stability.PHOENIX_PROJECT 2022/4/21, Add for PHOENIX_PROJECT

obj-$(CONFIG_OPL_FEATURE_PHOENIX) += opl_phoenix.o
opl_phoenix-y := op_bootprof.o phoenix_dump.o phoenix_watchdog.o phoenix_base.o
